### ISSUE TITLE
fis3 release production -d ./output  执行后没有编译呢

### ISSUE THREAD

**Issue by choukin** [fis-scaffold/react-redux-todo-npm#3]
D:\react\redux-example\fis3-react\react-redux-todo-npm>fis3 release production -d ./output

 [INFO] Currently running fis3 (C:\Users\xinzhou\AppData\Roaming\npm\node_modules\fis3)

 Ω ... 2.86s

D:\react\redux-example\fis3-react\react-redux-todo-npm>cd output

D:\react\redux-example\fis3-react\react-redux-todo-npm\output>dir
 驱动器 D 中的卷没有标签。
 卷的序列号是 FEB6-82E3

 D:\react\redux-example\fis3-react\react-redux-todo-npm\output 的目录

```
2016/07/09  16:41    <DIR>          .
2016/07/09  16:41    <DIR>          ..
2016/07/09  16:42               527 index.html
2016/07/09  16:41    <DIR>          static
```

```
           1 个文件            527 字节
           3 个目录 323,815,043,072 可用字节
```

release 到output里找不到 modules文件夹和压缩的index.js

**Comment by 2betop** [comment]
看似是没有安装 node_modules, 需要执行下 `npm install`

**Comment by 2betop** [comment]
跟 commonjs 最近的升级有关，请升级重新安装这个脚手架

**Comment by choukin** [comment]
升级解决
